// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// choose_cpp
int choose_cpp(int n, int k);
RcppExport SEXP _optpoly_choose_cpp(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(choose_cpp(n, k));
    return rcpp_result_gen;
END_RCPP
}
// degreeToMonomial_cpp
int degreeToMonomial_cpp(NumericVector degree, NumericVector monomialPrimes);
RcppExport SEXP _optpoly_degreeToMonomial_cpp(SEXP degreeSEXP, SEXP monomialPrimesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type monomialPrimes(monomialPrimesSEXP);
    rcpp_result_gen = Rcpp::wrap(degreeToMonomial_cpp(degree, monomialPrimes));
    return rcpp_result_gen;
END_RCPP
}
// monomialsToDegrees_cpp
NumericMatrix monomialsToDegrees_cpp(NumericVector monomials, NumericVector monomialPrimes);
RcppExport SEXP _optpoly_monomialsToDegrees_cpp(SEXP monomialsSEXP, SEXP monomialPrimesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type monomials(monomialsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type monomialPrimes(monomialPrimesSEXP);
    rcpp_result_gen = Rcpp::wrap(monomialsToDegrees_cpp(monomials, monomialPrimes));
    return rcpp_result_gen;
END_RCPP
}
// determineMonomialPosition_cpp
int determineMonomialPosition_cpp(NumericVector degree, NumericVector monomialPrimes, NumericVector momentVector);
RcppExport SEXP _optpoly_determineMonomialPosition_cpp(SEXP degreeSEXP, SEXP monomialPrimesSEXP, SEXP momentVectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type monomialPrimes(monomialPrimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type momentVector(momentVectorSEXP);
    rcpp_result_gen = Rcpp::wrap(determineMonomialPosition_cpp(degree, monomialPrimes, momentVector));
    return rcpp_result_gen;
END_RCPP
}
// evaluatePolynomial_cpp
double evaluatePolynomial_cpp(NumericVector point, NumericVector coefs, NumericMatrix degrees);
RcppExport SEXP _optpoly_evaluatePolynomial_cpp(SEXP pointSEXP, SEXP coefsSEXP, SEXP degreesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type point(pointSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type coefs(coefsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type degrees(degreesSEXP);
    rcpp_result_gen = Rcpp::wrap(evaluatePolynomial_cpp(point, coefs, degrees));
    return rcpp_result_gen;
END_RCPP
}
// computeDerivative_cpp
List computeDerivative_cpp(NumericVector coefs, NumericMatrix degrees, int dim, NumericVector monomialPrimes);
RcppExport SEXP _optpoly_computeDerivative_cpp(SEXP coefsSEXP, SEXP degreesSEXP, SEXP dimSEXP, SEXP monomialPrimesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type coefs(coefsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type degrees(degreesSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type monomialPrimes(monomialPrimesSEXP);
    rcpp_result_gen = Rcpp::wrap(computeDerivative_cpp(coefs, degrees, dim, monomialPrimes));
    return rcpp_result_gen;
END_RCPP
}
// createMosekSdpCoefficientMatrixFromDegrees_cpp
List createMosekSdpCoefficientMatrixFromDegrees_cpp(NumericVector coefs, NumericMatrix degrees, NumericVector monomialPrimes, NumericMatrix momentMatrixSparse);
RcppExport SEXP _optpoly_createMosekSdpCoefficientMatrixFromDegrees_cpp(SEXP coefsSEXP, SEXP degreesSEXP, SEXP monomialPrimesSEXP, SEXP momentMatrixSparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type coefs(coefsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type degrees(degreesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type monomialPrimes(monomialPrimesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type momentMatrixSparse(momentMatrixSparseSEXP);
    rcpp_result_gen = Rcpp::wrap(createMosekSdpCoefficientMatrixFromDegrees_cpp(coefs, degrees, monomialPrimes, momentMatrixSparse));
    return rcpp_result_gen;
END_RCPP
}
// createMosekSdpCoefficientMatrixFromMonomials_cpp
List createMosekSdpCoefficientMatrixFromMonomials_cpp(NumericVector coefs, NumericVector monomials, NumericMatrix momentMatrixSparse);
RcppExport SEXP _optpoly_createMosekSdpCoefficientMatrixFromMonomials_cpp(SEXP coefsSEXP, SEXP monomialsSEXP, SEXP momentMatrixSparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type coefs(coefsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type monomials(monomialsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type momentMatrixSparse(momentMatrixSparseSEXP);
    rcpp_result_gen = Rcpp::wrap(createMosekSdpCoefficientMatrixFromMonomials_cpp(coefs, monomials, momentMatrixSparse));
    return rcpp_result_gen;
END_RCPP
}
// createMosekSdpModelSkeleton_cpp
List createMosekSdpModelSkeleton_cpp(NumericVector nvar, NumericVector order, NumericVector isConstrained, NumericVector radius, NumericVector monomialPrimes, NumericMatrix momentMatrixSparse);
RcppExport SEXP _optpoly_createMosekSdpModelSkeleton_cpp(SEXP nvarSEXP, SEXP orderSEXP, SEXP isConstrainedSEXP, SEXP radiusSEXP, SEXP monomialPrimesSEXP, SEXP momentMatrixSparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type order(orderSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type isConstrained(isConstrainedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type monomialPrimes(monomialPrimesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type momentMatrixSparse(momentMatrixSparseSEXP);
    rcpp_result_gen = Rcpp::wrap(createMosekSdpModelSkeleton_cpp(nvar, order, isConstrained, radius, monomialPrimes, momentMatrixSparse));
    return rcpp_result_gen;
END_RCPP
}
// createMosekSdpModelSkeletonWithGradientIdeals_cpp
List createMosekSdpModelSkeletonWithGradientIdeals_cpp(NumericVector nvar, NumericVector orderObj, NumericVector orderMom, List gradientObj, NumericVector monomialPrimes, NumericMatrix momentMatrixSparse);
RcppExport SEXP _optpoly_createMosekSdpModelSkeletonWithGradientIdeals_cpp(SEXP nvarSEXP, SEXP orderObjSEXP, SEXP orderMomSEXP, SEXP gradientObjSEXP, SEXP monomialPrimesSEXP, SEXP momentMatrixSparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type orderObj(orderObjSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type orderMom(orderMomSEXP);
    Rcpp::traits::input_parameter< List >::type gradientObj(gradientObjSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type monomialPrimes(monomialPrimesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type momentMatrixSparse(momentMatrixSparseSEXP);
    rcpp_result_gen = Rcpp::wrap(createMosekSdpModelSkeletonWithGradientIdeals_cpp(nvar, orderObj, orderMom, gradientObj, monomialPrimes, momentMatrixSparse));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_optpoly_choose_cpp", (DL_FUNC) &_optpoly_choose_cpp, 2},
    {"_optpoly_degreeToMonomial_cpp", (DL_FUNC) &_optpoly_degreeToMonomial_cpp, 2},
    {"_optpoly_monomialsToDegrees_cpp", (DL_FUNC) &_optpoly_monomialsToDegrees_cpp, 2},
    {"_optpoly_determineMonomialPosition_cpp", (DL_FUNC) &_optpoly_determineMonomialPosition_cpp, 3},
    {"_optpoly_evaluatePolynomial_cpp", (DL_FUNC) &_optpoly_evaluatePolynomial_cpp, 3},
    {"_optpoly_computeDerivative_cpp", (DL_FUNC) &_optpoly_computeDerivative_cpp, 4},
    {"_optpoly_createMosekSdpCoefficientMatrixFromDegrees_cpp", (DL_FUNC) &_optpoly_createMosekSdpCoefficientMatrixFromDegrees_cpp, 4},
    {"_optpoly_createMosekSdpCoefficientMatrixFromMonomials_cpp", (DL_FUNC) &_optpoly_createMosekSdpCoefficientMatrixFromMonomials_cpp, 3},
    {"_optpoly_createMosekSdpModelSkeleton_cpp", (DL_FUNC) &_optpoly_createMosekSdpModelSkeleton_cpp, 6},
    {"_optpoly_createMosekSdpModelSkeletonWithGradientIdeals_cpp", (DL_FUNC) &_optpoly_createMosekSdpModelSkeletonWithGradientIdeals_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_optpoly(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
