# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

choose_cpp <- function(n, k) {
    .Call(`_optpoly_choose_cpp`, n, k)
}

degreeToMonomial_cpp <- function(degree, monomialPrimes) {
    .Call(`_optpoly_degreeToMonomial_cpp`, degree, monomialPrimes)
}

monomialsToDegrees_cpp <- function(monomials, monomialPrimes) {
    .Call(`_optpoly_monomialsToDegrees_cpp`, monomials, monomialPrimes)
}

determineMonomialPosition_cpp <- function(degree, monomialPrimes, momentVector) {
    .Call(`_optpoly_determineMonomialPosition_cpp`, degree, monomialPrimes, momentVector)
}

evaluatePolynomial_cpp <- function(point, coefs, degrees) {
    .Call(`_optpoly_evaluatePolynomial_cpp`, point, coefs, degrees)
}

computeDerivative_cpp <- function(coefs, degrees, dim, monomialPrimes) {
    .Call(`_optpoly_computeDerivative_cpp`, coefs, degrees, dim, monomialPrimes)
}

createMosekSdpCoefficientMatrixFromDegrees_cpp <- function(coefs, degrees, monomialPrimes, momentMatrixSparse) {
    .Call(`_optpoly_createMosekSdpCoefficientMatrixFromDegrees_cpp`, coefs, degrees, monomialPrimes, momentMatrixSparse)
}

createMosekSdpCoefficientMatrixFromMonomials_cpp <- function(coefs, monomials, momentMatrixSparse) {
    .Call(`_optpoly_createMosekSdpCoefficientMatrixFromMonomials_cpp`, coefs, monomials, momentMatrixSparse)
}

createMosekSdpModelSkeleton_cpp <- function(nvar, order, isConstrained, radius, monomialPrimes, momentMatrixSparse) {
    .Call(`_optpoly_createMosekSdpModelSkeleton_cpp`, nvar, order, isConstrained, radius, monomialPrimes, momentMatrixSparse)
}

createMosekSdpModelSkeletonWithGradientIdeals_cpp <- function(nvar, orderObj, orderMom, gradientObj, monomialPrimes, momentMatrixSparse) {
    .Call(`_optpoly_createMosekSdpModelSkeletonWithGradientIdeals_cpp`, nvar, orderObj, orderMom, gradientObj, monomialPrimes, momentMatrixSparse)
}

