# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

choose_cpp <- function(n, k) {
    .Call(`_optpoly_choose_cpp`, n, k)
}

getPrimes_cpp <- function(n) {
    .Call(`_optpoly_getPrimes_cpp`, n)
}

matrixToSparseTriplet_cpp <- function(mat, lowerTriangular) {
    .Call(`_optpoly_matrixToSparseTriplet_cpp`, mat, lowerTriangular)
}

vecToMatrix_cpp <- function(vectorOfEntries, dimMatrix, lowerTriangular) {
    .Call(`_optpoly_vecToMatrix_cpp`, vectorOfEntries, dimMatrix, lowerTriangular)
}

columnEchelon_cpp <- function(mat) {
    .Call(`_optpoly_columnEchelon_cpp`, mat)
}

degreeToMonomial_cpp <- function(degree, monomialPrimes) {
    .Call(`_optpoly_degreeToMonomial_cpp`, degree, monomialPrimes)
}

monomialsToDegrees_cpp <- function(monomials, monomialPrimes) {
    .Call(`_optpoly_monomialsToDegrees_cpp`, monomials, monomialPrimes)
}

determineMonomialPosition_cpp <- function(degree, monomialPrimes, momentVector) {
    .Call(`_optpoly_determineMonomialPosition_cpp`, degree, monomialPrimes, momentVector)
}

evaluatePolynomial_cpp <- function(point, coefs, degrees) {
    .Call(`_optpoly_evaluatePolynomial_cpp`, point, coefs, degrees)
}

computeDerivative_cpp <- function(coefs, degrees, dim, monomialPrimes) {
    .Call(`_optpoly_computeDerivative_cpp`, coefs, degrees, dim, monomialPrimes)
}

enumerateVector_cpp <- function(max, order) {
    .Call(`_optpoly_enumerateVector_cpp`, max, order)
}

createMosekSdpCoefficientMatrixFromDegrees_cpp <- function(coefs, degrees, monomialPrimes, momentMatrixSparse) {
    .Call(`_optpoly_createMosekSdpCoefficientMatrixFromDegrees_cpp`, coefs, degrees, monomialPrimes, momentMatrixSparse)
}

createMosekSdpCoefficientMatrixFromMonomials_cpp <- function(coefs, monomials, momentMatrixSparse) {
    .Call(`_optpoly_createMosekSdpCoefficientMatrixFromMonomials_cpp`, coefs, monomials, momentMatrixSparse)
}

createMosekSdpModelSkeletonLasserre_cpp <- function(nvar, order, isConstrained, isRectangular, bounds, radius, monomialPrimes, momentMatrixSparse) {
    .Call(`_optpoly_createMosekSdpModelSkeletonLasserre_cpp`, nvar, order, isConstrained, isRectangular, bounds, radius, monomialPrimes, momentMatrixSparse)
}

createMosekSdpModelSkeletonNieetal_cpp <- function(nvar, orderObj, orderMom, gradientObj, monomialPrimes, momentMatrixSparse) {
    .Call(`_optpoly_createMosekSdpModelSkeletonNieetal_cpp`, nvar, orderObj, orderMom, gradientObj, monomialPrimes, momentMatrixSparse)
}

createMosekQuadraticModelSkeleton_cpp <- function(coefs, degrees, monomialPrimes) {
    .Call(`_optpoly_createMosekQuadraticModelSkeleton_cpp`, coefs, degrees, monomialPrimes)
}

createGurobiQuadraticModelSkeleton_cpp <- function(coefs, degrees, monomialPrimes) {
    .Call(`_optpoly_createGurobiQuadraticModelSkeleton_cpp`, coefs, degrees, monomialPrimes)
}

